ARG TAG_NAME
FROM awiciroh/datastream-deps:${TAG_NAME} as datastream_base
RUN git clone --single-branch --branch nc_update2 https://github.com/JordanLaserGit/ngen-datastream.git
RUN pip3 install -e "/ngen-datastream/python"

RUN groupadd -r mygroup && useradd -r -g mygroup myuser
RUN chown -R myuser:mygroup /ngen-datastream

