ARG TAG="latest"
FROM awiciroh/datastream-deps:$TAG AS datastream_base
COPY ./ngen-datastream/ /ngen-datastream
RUN pip install -e /ngen-datastream/forcingprocessor
RUN groupadd -r mygroup && useradd -r -g mygroup myuser
RUN chown -R myuser:mygroup /ngen-datastream


