ARG TAG_NAME
FROM datastream-deps:${TAG_NAME} as datastream_base

RUN pip install -e /ngen-datastream/python

RUN groupadd -r mygroup && useradd -r -g mygroup myuser
RUN chown -R myuser:mygroup /ngen-datastream
