---
#--------------------------------------------------------------------------------
log_parameters:
    #----------
    showtiming: True
    log_level: INFO
#--------------------------------------------------------------------------------
network_topology_parameters:
    #----------
    supernetwork_parameters:
        #----------
        geo_file_path: ./config/cat-2863657_subset.gpkg
        columns:
            key: "id"
            downstream: "toid"
            dx: "Length_m"
            n: "n"
            ncc: "nCC"
            s0: "So"
            bw: "BtmWdth"
            waterbody: "WaterbodyID"
            gages: "gage"
            tw: "TopWdth"
            twcc: "TopWdthCC"
            musk: "MusK"
            musx: "MusX"
            cs: "ChSlp"
            alt: "alt"
    waterbody_parameters:
        #----------
        break_network_at_waterbodies: False

#--------------------------------------------------------------------------------
compute_parameters:
    #----------
    parallel_compute_method: by-subnetwork-jit-clustered # serial
    compute_kernel: V02-structured
    assume_short_ts: True
    subnetwork_target_size: 50
    cpu_pool: 16
    restart_parameters:
        #----------
        #wrf_hydro_channel_restart_file: restart/HYDRO_RST.2020-08-26_00:00_DOMAIN1
        #wrf_hydro_channel_ID_crosswalk_file: domain/RouteLink_NWMv2.1.nc
        #wrf_hydro_waterbody_restart_file: restart/HYDRO_RST.2020-08-26_00:00_DOMAIN1
        #wrf_hydro_waterbody_ID_crosswalk_file    : domain/LAKEPARM_NWMv2.1.nc
        #wrf_hydro_waterbody_crosswalk_filter_file: domain/LAKEPARM_NWMv2.1.nc
        start_datetime: 2010-01-01 00:00:00 #"2022-08-24 13:00:00"
    #hybrid_parameters:
    #    run_hybrid_routing: True
    #    diffusive_domain  : domain/coastal_domain.yaml
    #    use_natl_xsections: False
    #    topobathy_domain  : # domain/final_diffusive_natural_xs.nc
    #    run_refactored_network: False
    #    refactored_domain: # domain/unit_test_noRS/refactored_coastal_domain.yaml
    #    refactored_topobathy_domain: # domain/refac_final_diffusive_natural_xs.nc
    #    coastal_boundary_domain: domain/coastal_boundary_domain.yaml
    forcing_parameters:
        #----------
        qts_subdivisions: 12
        dt: 300 # [sec] 300 == 5 minutes
        qlat_input_folder: ./outputs/ngen/
        qlat_file_pattern_filter: "nex-*"

        #binary_nexus_file_folder: ./outputs/parquet/ # if nexus_file_pattern_filter="nex-*" and you want it to reformat them as parquet, you need this
        #coastal_boundary_input_file : channel_forcing/schout_1.nc
        nts: 288.0 #288 for 1day
        max_loop_size: 288.0 # [number of timesteps]
        # max_loop_size == nts so that output is single file
    data_assimilation_parameters:
        #    #----------
        #    usgs_timeslices_folder   : #usgs_TimeSlice/
        #    usace_timeslices_folder  : #usace_TimeSlice/
        #    timeslice_lookback_hours : #48
        #    qc_threshold             : #1
        streamflow_da:
            #----------
            streamflow_nudging: False
            diffusive_streamflow_nudging: False
        #        gage_segID_crosswalk_file     : # domain/RouteLink_NWMv2.1.nc
        #        crosswalk_gage_field          : # 'gages'
        #        crosswalk_segID_field         : # 'link'
        #        wrf_hydro_lastobs_file        :
        #        lastobs_output_folder         : lastobs/
        reservoir_da:
            #----------
            reservoir_persistence_da:
                #----------
                reservoir_persistence_usgs: False
                reservoir_persistence_usace: False
            reservoir_rfc_da:
                #----------
                reservoir_rfc_forecasts: False
                reservoir_rfc_forecasts_time_series_path: rfc_timeseries/
                reservoir_rfc_forecasts_lookback_hours: 28
                reservoir_rfc_forecasts_offset_hours: 28
#--------------------------------------------------------------------------------
output_parameters:
    #----------
    #test_output: outputs/lcr_flowveldepth.pkl
    lite_restart:
        #----------
        lite_restart_output_directory: restart/
    lakeout_output: lakeout/
    stream_output:
        stream_output_directory: outputs/troute/
        stream_output_time: 24.0 #number of internal_frequency timesteps per output file
        stream_output_type: ".nc" #please select only between netcdf '.nc' or '.csv' or '.pkl'
        stream_output_internal_frequency: 60 #[min] it should be order of 5 minutes. For instance if you want to output every hour put 60
