FROM alpine:3.18
RUN apk add --no-cache wget
RUN wget https://github.com/LynkerIntel/hfsubset/releases/download/hfsubset-release-9/hfsubset-linux_amd64.tar.gz
RUN tar -xzvf hfsubset-linux_amd64.tar.gz