# CONFIGURATION FILE FOR NGEN-DATASTREAM

START_DATE="DAILY"
# END_DATE=""
# DATA_PATH=""
# RESOURCE_PATH=""
# RELATIVE_TO=""
SUBSET_ID_TYPE="hl_uri"
SUBSET_ID="Gages-04185000"
HYDROFABRIC_VERSION="v20"

