name: Build, Test, and Push Docker Containers

on:
  pull_request:
    branches:
      - main    
    paths:      
      - 'docker/**'
      - 'forcingprocessor/**'
      - 'scripts/docker_build.sh'  
      - 'python_tools/**'
      - '.github/workflows/forcingprocessor.yml'
      - '.github/workflows/datastream_python.yml'        

jobs:
  build-and-test-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}  
        
    - name: Build x86 and load
      run: |
        ./scripts/docker_builds.sh -e -f -d -m linux/amd64 -t tmp 

    - name: Set Docker tag
      run: |
        
        # NGIAB will default to latest   

    - name: Test stream with hf v2.1
      run: |
        export DS_TAG=tmp && export FP_TAG=tmp && rm -rf $(pwd)/data/datastream_test && ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g https://ngen-datastream.s3.us-east-2.amazonaws.com/palisade.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json

    - name: Test stream with hf v2.2
      run: |
        export DS_TAG=tmp && export FP_TAG=tmp && rm -rf $(pwd)/data/datastream_test && ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-09_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json

    - name: Save to dockerhub
      run: |
        ./scripts/docker_builds.sh -e -f -d -m linux/amd64,linux/arm64 -t latest -p