name: Build and Test Datastream Docker Containers on ARM
on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'forcingprocessor/**'
      - 'scripts/**'  
      - 'python_tools/**'
      - '.github/workflows/forcingprocessor.yml'
      - '.github/workflows/datastream_python.yml'  

  pull_request:
    branches:
      - main    
    paths:      
      - 'docker/**'
      - 'forcingprocessor/**'
      - 'scripts/**'  
      - 'python_tools/**'
      - '.github/workflows/forcingprocessor.yml'
      - '.github/workflows/datastream_python.yml'           

jobs:
  build-test-docker-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.aws_access_key_id }}
          aws configure set aws_secret_access_key ${{ secrets.aws_secret_access_key }}
          aws configure set region us-east-1        
      - name: Build AWS Infra
        run: |
          cd research_datastream/terraform
          terraform init
          terraform validate
          terraform apply -var-file=./test/variables_gitactions.tfvars -auto-approve
          sleep 60
      - name: Build and Test arm docker containers with AWS infra
        run : |
          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat ./sm_ARN.txt) --name docker_builder_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://test/execution_gp_arm_docker_buildNtester.json" --region us-east-1 --query 'executionArn' --output text); echo "Execution ARN: $execution_arn"; status="RUNNING"; while [ "$status" != "SUCCEEDED" ]; do status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text); echo "Current status: $status"; if [ "$status" == "FAILED" ]; then echo "State machine execution failed!"; exit 1; fi; sleep 5; done; echo "State machine execution succeeded!"
      - name: Tear down infra
        if: always()
        run : |
          terraform destroy -var-file=./test/variables_gitactions.tfvars -auto-approve
          sleep 60

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}   

      - name: Push docker containers
        run: |
          cd ../.. && ./scripts/docker_builds.sh -p      
          
