name: Build, Test, and Push Datastream Docker Containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'forcingprocessor/**'
      - 'scripts/**'  
      - 'python_tools/**'
      - '!docs/**'
      - '!scripts/README.md'    
      - '!docker/README.md'  
      - '!forcingprocessor/README.md' 
      - '!python_tools/README.md'     

permissions:
  contents: read

jobs:
  build-test-push-docker-x86:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1    
        
    - name: Install packages for datastream
      run: |
        curl -L -O https://github.com/lynker-spatial/hfsubsetCLI/releases/download/v1.1.0/hfsubset-v1.1.0-linux_amd64.tar.gz && tar -xzvf hfsubset-v1.1.0-linux_amd64.tar.gz && sudo mv ./hfsubset /usr/bin/hfsubset && sudo apt-get install git pip pigz -y        

    - name: Build docker containers
      run : |        
        ./scripts/docker_builds.sh -e -f -d -t latest-x86

    - name: Test docker containers
      run : |
        curl -L -O https://ngen-datastream.s3.us-east-2.amazonaws.com/palisade.gpkg
        export DS_TAG=latest-x86 FP_TAG=latest-x86 && ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g $(pwd)/palisade.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json -n 4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}   

    - name: Push docker containers
      run: |
        ./scripts/docker_builds.sh -p      
