name: Build and Test Datastream Docker compose on x86

on:
  workflow_dispatch:
  push: 
    paths:      
      - 'docker/**'
      - 'forcingprocessor/**'
      - 'scripts/**'  
      - 'python_tools/**'
      - '!docs/**'
      - '!scripts/README.md'    
      - '!docker/README.md'  
      - '!forcingprocessor/README.md' 
      - '!python_tools/README.md'            

permissions:
  contents: read      

jobs:
  build-test-docker-x86:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}        

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Build docker containers
      run: |
        # export ARCH=$(uname -m)
        # docker compose -f docker/docker-compose.yml build datastream-deps
        docker compose -f docker/docker-compose.yml build datastream
        docker compose -f docker/docker-compose.yml build forcingprocessor

    - name: Test docker containers
      run : |
        curl -L -O https://ngen-datastream.s3.us-east-2.amazonaws.com/palisade.gpkg
        ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g $(pwd)/palisade.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
