name: Build, Test, and Push Datastream Docker Containers

on:
  workflow_run:
    workflows: ["Test Forcing Processor","Test Datastream Python"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build_test_push_docker.yml'
  pull_request:
    branches:
      - main    
    paths:      
      - '.github/workflows/build_test_push_docker.yml'      

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ secrets.aws_secret_access_key }}
        aws configure set region us-east-1      

    - name: Build docker containers
      run : |        
        ./scripts/docker_builds.sh

    - name: Test docker containers
      run : |
        hfsubset -w medium_range -s nextgen -v 2.1.1 -l divides,flowlines,network,nexus,forcing-weights,flowpath-attributes,model-attributes -o palisade.gpkg -t hl Gages-09106150
        ./scripts/stream.sh -s 202006200100 -e 202006210000 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g $(pwd)/palisade.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json -n 4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}   

    - name: Push docker containers
      run: |
        export PLATFORM_TAG=x86
        docker push awiciroh/datastream-deps:latest$PLATORM_TAG
        docker push awiciroh/datastream:latest$PLATORM_TAG
        docker push awiciroh/forcingprocessor:latest$PLATORM_TAG        
