# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Datastream Python
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'python_tools/**'
      - '!python_tools/README.md'
  pull_request:
    branches:
      - main    
    paths:      
      - 'python_tools/**'
      - '!python_tools/README.md'
      
permissions:
  contents: read
jobs:
  test-python-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install -e ./python_tools
        uv pip install pytest

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        python -m pytest -vv python_tools/
