# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Datastream Python
on:
  push:
    branches:
      - main
    paths:
      - 'python_tools/**'
      - '.github/workflows/datastream_python.yaml'
      - '.github/workflows/build_test_docker_x86.yaml'
  pull_request:
    branches:
      - main    
    paths:      
      - 'python_tools/**'
      - '.github/workflows/datastream_python.yaml'
      - '.github/workflows/build_test_docker_x86.yaml'
permissions:
  contents: read
jobs:
  test-python-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./python_tools
        pip install pytest

    - name: Test with pytest
      run: |
        python -m pytest -vv python_tools/
