# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Forcing Processor Output Options
on:
  push:
    branches:
      - main
    paths:
      - 'forcingprocessor/**'
      - '.github/workflows/forcingprocessor.yaml'
      - '.github/workflows/build_test_docker_x86.yaml'
  pull_request:
    branches:
      - main    
    paths:      
      - 'forcingprocessor/**'
      - '.github/workflows/forcingprocessor.yaml'
      - '.github/workflows/build_test_docker_x86.yaml'

permissions:
  contents: read
jobs:
  test-forcingprocessor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1           
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./forcingprocessor
        pip install pytest

    - name: Test with pytest
      run: |
        cd forcingprocessor
        # netcdf already tested
        python -m pytest -vv -k test_csv_output_type
        python -m pytest -vv -k test_parquet_output_type

