# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Forcing Processor
on:
  push:
    branches:
      - main
    paths:
      - 'forcingprocessor/**'
      - '.github/workflows/forcingprocessor.yml'
  pull_request:
    branches:
      - main    
    paths:      
      - 'forcingprocessor/**'
      - '.github/workflows/forcingprocessor.yml'
permissions:
  contents: read
jobs:
  test-forcingprocessor:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1           
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./forcingprocessor
        pip install pytest

    - name: Test with pytest
      run: |
        cd forcingprocessor
        python -m pytest -vv --deselect="tests/test_forcingprocessor.py::test_google_cloud_storage" --deselect="tests/test_forcingprocessor.py::test_gcs" --deselect="tests/test_forcingprocessor.py::test_gs" --deselect="tests/test_forcingprocessor.py::test_ciroh_zarr" --deselect="tests/test_forcingprocessor.py::test_nomads_post_processed" --deselect="tests/test_forcingprocessor.py::test_retro_ciroh_zarr"
        python -m pytest -vv -k test_google_cloud_storage 
        python -m pytest -vv -k test_gs 
        python -m pytest -vv -k test_gcs 
