# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Forcing Processor for NRDS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'forcingprocessor/**'
      - '!forcingprocessor/README.md'
  pull_request:
    branches:
      - main    
    paths:      
      - 'forcingprocessor/**'
      - '!forcingprocessor/README.md'

permissions:
  contents: read
jobs:
  test-forcingprocessor-nrds:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Extract Python version from setup.py
      id: pyver
      run: |
        # Extract the python_requires line
        VERSION=$(python -c "import re; text=open('forcingprocessor/setup.py').read(); m=re.search(r'python_requires\s*=\s*[\"\\']([^\"\\']+)[\"\\']', text); print(m.group(1) if m else '')")
        # Pick the lowest supported version
        VERSION=$(echo $VERSION | sed -E 's/[^0-9.<>!=, ]//g' | awk -F'[<>=, ]+' '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ steps.pyver.outputs.version }}

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./forcingprocessor
        pip install pytest

    - name: Test with pytest
      run: |
        cd forcingprocessor
        python -m pytest -vv tests/test_nrds_fp.py