# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Forcing Processor for NRDS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'forcingprocessor/**'
      - '!forcingprocessor/README.md'
  pull_request:
    branches:
      - main    
    paths:      
      - 'forcingprocessor/**'
      - '!forcingprocessor/README.md'

permissions:
  contents: read
jobs:
  test-forcingprocessor-nrds:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Extract Python version from setup.cfg
      id: pyver
      run: |
        # Read python_requires from setup.cfg
        VERSION=$(awk -F'>=' '/^python_requires/ {print $2}' forcingprocessor/setup.cfg | tr -d ' ')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.pyver.outputs.version }}

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1           
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./forcingprocessor
        pip install pytest

    - name: Test with pytest
      run: |
        cd forcingprocessor
        python -m pytest -vv tests/test_nrds_fp.py
