name: Create Multi-Platform Manifest
on:
  workflow_run:
    workflows:
      - "Build, Test, and Push Datastream Docker Containers on ARM"
    types:
      - completed  
      
  pull_request:
    branches:
      - main    
    paths:      
      - '.github/workflows/manifest_docker_containers.yaml'    

jobs:
  create-multi-platform-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push multi-platform image
        run: |
          docker buildx create --use
          docker buildx imagetools create \
            -t awiciroh/datastream-deps:latest \
            awiciroh/datastream-deps:latest-x86 \
            awiciroh/datastream-deps:latest-arm64

          docker buildx create --use
          docker buildx imagetools create \
            -t awiciroh/datastream:latest \
            awiciroh/datastream:latest-x86 \
            awiciroh/datastream:latest-arm64       

          docker buildx create --use
          docker buildx imagetools create \
            -t awiciroh/forcingprocessor:latest \
            awiciroh/forcingprocessor:latest-x86 \
            awiciroh/forcingprocessor:latest-arm64                       
