name: Test Community Hydrofabric

on:
  workflow_dispatch:     

permissions:
  contents: read
      
jobs:
  test-vpu-01:
    runs-on: ubuntu-latest
    name: Test VPU 01
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Test VPU 01
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=01    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json

  test-vpu-02:
    runs-on: ubuntu-latest
    name: Test VPU 02
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Test VPU 02
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=02    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

  test-vpu-03W:
    runs-on: ubuntu-latest
    name: Test VPU 03W
    steps:
    - name: Checkout code
      uses: actions/checkout@v2          
    - name: Test VPU 03W
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=03W    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
    
  test-vpu-03N:
    runs-on: ubuntu-latest
    name: Test VPU 03N
    steps:
    - name: Checkout code
      uses: actions/checkout@v2          
    - name: Test VPU 03N
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=03N    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
  
  test-vpu-03S:
    runs-on: ubuntu-latest
    name: Test VPU 03S
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Test VPU 03S
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=03S    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  
  test-vpu-04:
    runs-on: ubuntu-latest
    name: Test VPU 04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Test VPU 04
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=04   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

  test-vpu-05:
    runs-on: ubuntu-latest
    name: Test VPU 05
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Test VPU 05
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=05   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json

  test-vpu-06:
    runs-on: ubuntu-latest
    name: Test VPU 06
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Test VPU 06
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=06  
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

  test-vpu-07:
    runs-on: ubuntu-latest
    name: Test VPU 07
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test VPU 07
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=07
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  test-vpu-08:
    runs-on: ubuntu-latest
    name: Test VPU 08
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test VPU 08
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=08 
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
  
  test-vpu-09:
    runs-on: ubuntu-latest
    name: Test VPU 09
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Test VPU 09
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=09   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

  test-vpu-10L:
    runs-on: ubuntu-latest
    name: Test VPU 10L
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 10L
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=10L  
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

  test-vpu-10U:
    runs-on: ubuntu-latest
    name: Test VPU 10U
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 10U
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=10U 
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json

  test-vpu-11:
    runs-on: ubuntu-latest
    name: Test VPU 11
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test VPU 11
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=11 
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

  test-vpu-12:
    runs-on: ubuntu-latest
    name: Test VPU 12
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 12
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=12
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

  test-vpu-13:
    runs-on: ubuntu-latest
    name: Test VPU 13
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 13
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=13
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
    
  test-vpu-14:
    runs-on: ubuntu-latest
    name: Test VPU 14
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 14
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=14   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
    
  test-vpu-15:
    runs-on: ubuntu-latest
    name: Test VPU 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 15
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=15
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  
  test-vpu-16:
    runs-on: ubuntu-latest
    name: Test VPU 16
    steps:
    - name: Checkout code
      uses: actions/checkout@v2         
    - name: Test VPU 16
      if: always()
      run: |        
          sudo rm -rf $(pwd)/data/datastream_test    
          export VPU=16
          ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  
  test-vpu-17:
    runs-on: ubuntu-latest
    name: Test VPU 17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 17
      if: always()
      run: |        
          sudo rm -rf $(pwd)/data/datastream_test    
          export VPU=17
          ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
      
  test-vpu-18:
    runs-on: ubuntu-latest
    name: Test VPU 18
    steps:
    - name: Checkout code
      uses: actions/checkout@v2           
    - name: Test VPU 18
      if: always()
      run: |        
          sudo rm -rf $(pwd)/data/datastream_test    
          export VPU=18
          ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
                        