name: Test hfsubset v2.2 Integration

on:
  workflow_dispatch:  
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/datastream'    
      
  push:
    branches:
      - main
    paths:
      - 'scripts/datastream'     

permissions:
  contents: read

jobs:
  test-hfsubset-v2-2-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      

    - name: Build docker containers
      run : |        
        ./scripts/docker_builds.sh -f -d    
        
    - name: Install packages for datastream
      run: |
        curl -L -O https://github.com/lynker-spatial/hfsubsetCLI/releases/download/v1.1.0/hfsubset-v1.1.0-linux_amd64.tar.gz && tar -xzvf hfsubset-v1.1.0-linux_amd64.tar.gz && sudo mv ./hfsubset /usr/bin/hfsubset
              
    - name: Get geopackage v2.2
      run: |
        hfsubset -o ./divides_nexus.gpkg -r "2.2" -t hl "Gages-06752260"

    - name: Test datastream with v2.2 options
      if: always()
      run: |
        ./scripts/datastream -s 202006200100 -e 202006200200 -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -I "Gages-09106150" -i hl -v 2.2 -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
            