name: Test Research DataStream ForcingProcessing
on:
  workflow_dispatch:     
  push:
    branches:
      - main
    paths:
      - 'forcingprocessor/**'
      - '!forcingprocessor/README.md'      
  pull_request:
    branches:
      - main    
    paths:      
      - 'forcingprocessor/**'
      - '!forcingprocessor/README.md'  

permissions:
  contents: read
jobs:
  test-research-datastream-forcingprocessing:
    runs-on: ubuntu-latest
    env:
      VPU: fp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install --upgrade awscli

      - name: Download and modify execution JSON
        run: |
          cd research_datastream/terraform_community
          # Download the execution JSON
          aws s3 cp s3://ciroh-community-ngen-datastream/v2.2/ngen.20250801/forcing_short_range/00/metadata/execution.json execution.json
          # Remove specified fields and update TagSpecifications
          jq 'del(.instance_parameters.MaxCount, .instance_parameters.MinCount, .instance_parameters.InstanceId, .t0, .ii_s3_object_checked, .retry_attempt, .region) | .instance_parameters.TagSpecifications = [{"ResourceType": "instance", "Tags": [{"Key": "Project", "Value": "fp_test_git_actions"}]}]' | .commands |= map(sub("--S3_PREFIX(?i) \\K[^ ]+"; "\'tests/short_range/${{ env.VPU }}\'")) execution.json > temp.json
          
      - name: Check and create AWS key pair
        run: |
          cd research_datastream/terraform_community
          if ! aws ec2 describe-key-pairs --key-names "actions_key" --query 'KeyPairs[0].KeyName' --output text 2>/dev/null; then 
            aws ec2 create-key-pair --key-name "actions_key" --query 'KeyName' --output text && echo "Key pair 'actions_key' created in AWS"; 
          else 
            echo "Key pair 'actions_key' already exists"; 
          fi

      - name: Start and monitor Step Functions execution
        run: |
          cd research_datastream/terraform_community
          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat ./sm_ARN.txt) --name fp_test_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://temp.json" --region us-east-1 --query 'executionArn' --output text)
          echo "Execution ARN: $execution_arn"
          status="RUNNING"
          while [ "$status" != "SUCCEEDED" ]; do
            status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text)
            echo "Current status: $status"
            if [ "$status" == "FAILED" ]; then
              echo "State machine execution failed!"
              exit 1
            fi
            sleep 5
          done
          echo "State machine execution succeeded!"

      - name: Verify output file
        run: |
          cd research_datastream/terraform_community
          curl -fSs -o test.txt https://ciroh-community-ngen-datastream.s3.amazonaws.com/tests/short_range/${{ env.VPU }}/merkdir.file || { echo "Error: File not found or request failed"; exit 1; }          