name: Test TEEHR Integration

on:
  workflow_dispatch:  
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/datastream'    
      
  push:
    branches:
      - main
    paths:
      - 'scripts/datastream'      

permissions:
  contents: read  

jobs:
  test-datastream-options:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1    
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        echo $AWS_ACCESS_KEY_ID
        echo $AWS_SECRET_ACCESS_KEY

    - name: Build docker containers
      run : |        
        ./scripts/docker_builds.sh -f -d        

    - name: Get geopackage 
      run: |
        curl -L -O https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-09_subset.gpkg      
      
    - name: TEEHR integration test
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test
        ./scripts/datastream -s DAILY -C NWM_V3_SHORT_RANGE -d $(pwd)/data/datastream_test -g $(pwd)/vpu-09_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json -E True

        
           