name: Datastream Test

on:
  push:
    branches:
      - main

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:35
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
      
    - name: Install dependencies
      run: |
        $(pwd)/scripts/install.sh
        aws configure set aws_access_key_id ${{ secrets.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ secrets.aws_secret_access_key }}
        $(pwd)/tests/scripts/test_stream.sh -d $(pwd)
