name: Test Community Hydrofabric

on:
  push:
    branches:
      - main
    paths:      
      - 'research_datastream/**'
      - '.github/workflows/test_community_hydrofabric.yaml'    
     
  pull_request:
    branches:
      - main  
    paths:      
      - 'research_datastream/**'    
      - '.github/workflows/test_community_hydrofabric.yaml'      

jobs:
  test-datastream-options:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1    
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Test VPU 01
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=01    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json

    - name: Test VPU 02
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=02    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

    - name: Test VPU 03W
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=03W    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
    
    - name: Test VPU 03N
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=03N    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
  
    - name: Test VPU 03S
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=03S    
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  
    - name: Test VPU 04
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=04   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

    - name: Test VPU 05
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=05   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
  
    - name: Test VPU 06
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=06  
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  
    - name: Test VPU 07
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=07
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

    - name: Test VPU 08
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=08 
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
    
    - name: Test VPU 09
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=09   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

    - name: Test VPU 10L
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=10L  
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

    - name: Test VPU 10U
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=10U 
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
    
    - name: Test VPU 11
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=11 
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

    - name: Test VPU 12
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=12
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        

    - name: Test VPU 13
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=13
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
    
    - name: Test VPU 14
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=14   
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
    - name: Test VPU 15
      if: always()
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=15
        ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  
    - name: Test VPU 16
      if: always()
      run: |        
          sudo rm -rf $(pwd)/data/datastream_test    
          export VPU=16
          ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
  
    - name: Test VPU 17
      if: always()
      run: |        
          sudo rm -rf $(pwd)/data/datastream_test    
          export VPU=17
          ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json
      
    - name: Test VPU 18
      if: always()
      run: |        
          sudo rm -rf $(pwd)/data/datastream_test    
          export VPU=18
          ./scripts/datastream -s DAILY -C NWM_SHORT_RANGE_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
                        