name: Test Community Hydrofabric

on:
  push:
    branches:
      - main
    paths:      
      - 'research_datastream/**'
      - '.github/workflows/test_community_hydrofabric.yaml'    
     
  pull_request:
    branches:
      - main  
    paths:      
      - 'research_datastream/**'    
      - '.github/workflows/test_community_hydrofabric.yaml'      

jobs:
  test-datastream-options:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      

    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1    
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Test VPU 01
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=01    
        ./scripts/datastream -s DAILY -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json

    - name: Test VPU 02
      run: |        
        sudo rm -rf $(pwd)/data/datastream_test    
        export VPU=02    
        ./scripts/datastream -s DAILY -C NWM_RETRO_V3 -d $(pwd)/data/datastream_test -g https://communityhydrofabric.s3.us-east-1.amazonaws.com/hydrofabrics/community/VPU/vpu-${VPU}_subset.gpkg -R $(pwd)/configs/ngen/realization_sloth_nom_cfe_pet.json        
